### PR TITLE
SystemTray Notifications (not Tested)

### PR DESCRIPTION
**Pull request by k-304**
A quick update for the SystemTray Notifications. Start Notification works, finish NC not tested yet.

Disabled Signing because of an error at my office PC.

### CODE REVIEW

**Comment by MrCryptoT** [comment]
Hey great. 
I'll have a look at it. 
If i have the time I'll test it... 

Do you know if the signing thinkg has Impact on something else? (If it might lead to bugs? I don't really know what it does - but I think it just writes the Information of your Computer into the Built exe? either way, can wait until we see us ins chool again.)

**Comment by k-304** [comment]
No I just googled how to solve the signing problem xD

I'm currently writing the Code for the inactive "Change Folder Dir"
Button... I'm curently doing it without an extra Form. I've pushed it into
my Repo but I couln't finish it yet. Maybe tomorrow... I found an easy way
to change a Folder Pair. I'll let the User choose between editing the
Source or Backup Path. If he wants to edit both (like because of they are
false) he can delete it and add a comletely new Path.

Yea there just like 4 weeks of school break between our next school day...
Have a great time without us school mates :D

Tom notifications@github.com schrieb am Do., 23. Juli 2015 um 16:50 Uhr:

**Comment by MrCryptoT** [comment]
If it s okay for you, try to implement it within the timetable.vb clas.s... 
then we only Need 1 Form =) (Cahgne the "edit time config" button to "edit Folder cnfig" or somethig like that... 
So that there is only 1 button to edit Folders where u can coose the times etc AND manipulate the directories if you wish so. 
Hope you know how I mena that... 
Otherwise, please write me and I'll call U back. 
you'll surely do a good Job I'm sure =) . 

I know... I know ;) otherwise we ll have to disscuss this over the phone.
Oh and, the notify Icon works. 
Tested and it successfully tells the user the wantd Information. 
Nice bro =) 

Will hear from you  =). Have a good one_ü¨

**Comment by k-304** [comment]
Yea I know what you mean... this is absoloutly better then using different Forms / Buttons.
I'll start it tomorrow and do some layout changes... Then I'll write the code for it.
You'll reciev my PR as far as there is something new designating... ;)

**Pull request merged**
